version: '3'
services:
  app:
    build: .
    depends_on:
      - redis-server
    env_file:
      - .env.dev
    networks:
      - app_net
    command: ["/app/.venv/bin/python", "main.py"]

  redis-server:
    image: redis:7.4-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  redis-data:
